### Матрицы и матричные операции. Часть 1

##### 1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

In [1]:
import numpy as np

а) $AB$ – нельзя умножать, $BA$ – нельзя умножать

б) $AB$ – $2\times3$, $BA$ – нельзя умножать

в) $AB$ – $8\times8$, $BA$ – $3\times3$

г) $AB$ – $4\times4$, $BA$ – $4\times4$

In [3]:
print('б1) AB =', np.dot(np.ones((2,5)), np.ones((5,3))).shape)
print('в1) AB =', np.dot(np.ones((8,3)), np.ones((3,8))).shape)
print('в2) BA =', np.dot(np.ones((3,8)), np.ones((8,3))).shape)
print('г) AB = BA =', np.dot(np.ones((4,4)), np.ones((4,4))).shape)

б1) AB = (2, 3)
в1) AB = (8, 8)
в2) BA = (3, 3)
г) AB = BA = (4, 4)


##### 2.  Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A + B = B + A = \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix} + \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\ 
3 & 5 
\end{pmatrix}
$$$$AB = \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
1\cdot4-2\cdot0 & 1\cdot(-1)-2\cdot5 \\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5 
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\ 
12 & -3 
\end{pmatrix}
$$$$BA = \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix} = \begin{pmatrix}
4\cdot1-1\cdot3 & 4\cdot(-2)-1\cdot0 \\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0 
\end{pmatrix} = \begin{pmatrix}
1 & -8 \\ 
15 & 0 
\end{pmatrix}$$

In [4]:
A = np.matrix([[1, -2], [3, 0]])
B = np.matrix([[4, -1], [0, 5]])

print('A + B = B + A =\n', A + B)
print('A x B =\n', np.dot(A, B))
print('B x A =\n', np.dot(B, A))

A + B = B + A =
 [[ 5 -3]
 [ 3  5]]
A x B =
 [[  4 -11]
 [ 12  -3]]
B x A =
 [[ 1 -8]
 [15  0]]


##### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A - 2B + 4C = 3\begin{pmatrix}
1 & 7 \\ 
3 & -6 
\end{pmatrix} - 2\begin{pmatrix}
0 & 5 \\ 
2 & -1 
\end{pmatrix} + 4\begin{pmatrix}
2 & -4 \\ 
1 & 1 
\end{pmatrix} = \begin{pmatrix}
3 & 21 \\ 
9 & -18 
\end{pmatrix} + \begin{pmatrix}
0 & -10 \\ 
-4 & 2 
\end{pmatrix} + \begin{pmatrix}
8 & -16 \\ 
4 & 4 
\end{pmatrix} = \begin{pmatrix}
3+0+8 & 21-10-16 \\ 
9-4+4 & -18+2+4 
\end{pmatrix} = \begin{pmatrix}
11 & -5 \\ 
9 & -12 
\end{pmatrix}$$

In [7]:
A = np.matrix([[1, 7], [3, -6]])
B = np.matrix([[0, 5], [2, -1]])
C = np.matrix([[2, -4], [1, 1]])

print('3A - 2B + 4C =\n', 3*A - 2*B + 4*C)

3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]


##### 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

$$A^T = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3\end{pmatrix}
$$$$AA^T = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\
2 & 3 
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3 \\
5\cdot4-2\cdot1 & 5\cdot5-2\cdot(-2) & 5\cdot2-2\cdot3 \\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}
$$$$A^TA = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\
2 & 3 
\end{pmatrix} = \begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3 \\
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot(-2)+3\cdot3
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}$$

In [8]:
A = np.matrix([[4, 1], [5, -2], [2, 3]])

print('A.T =\n', A.T)
print('A*A.T =\n', np.dot(A, A.T))
print('A.T*A =\n', np.dot(A.T, A))

A.T =
 [[ 4  5  2]
 [ 1 -2  3]]
A*A.T =
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T*A =
 [[45  0]
 [ 0 14]]


##### 5.* Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [13]:
import random
 
def matrixmult(m1, m2):
    s=0     #сумма
    t=[]    #временная матрица
    m3=[]   # конечная матрица
    if len(m2) != len(m1[0]):
        print ("Матрицы не могут быть перемножены")        
    else:
        r1 = len(m1) #количество строк в первой матрице
        c1 = len(m1[0]) #Количество столбцов в 1   
        r2 = c1           #и строк во 2ой матрице
        c2 = len(m2[0])  # количество столбцов во 2ой матрице
        for z in range(0, r1):
            for j in range(0, c2):
                for i in range(0, c1):
                   s = s + m1[z][i] * m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
    return m3
 
def creatematrix(r, c):
    t=[]
    m=[]
    for i in range(0, r):
        for j in range(0, c):
            t.append(random.randint(1, 10))
        m.append(t)
        t=[]
    return m
 
c1 = 1
r2 = 2
while c1 != r2:
    print("Кол-во столбцов в первой матрице должно быть = кол-ву строк 2 матрицы")
    r1 = int(input ('Введите кол-во строк для первой матрицы >'))
    c1 = int(input ('Введите кол-во столюцов для 1 матрицы >'))
    r2 = int(input ('Введите кол-во строк для второй матрицы >'))
    c2 = int(input ('Введите кол-во столбцов для 2 матрицы >'))
    
m1 = creatematrix(r1, c1)
m2 = creatematrix(r2, c2)
    
print(m1)
print(m2)
 
m3 = matrixmult(m1, m2)
print(m3)

Кол-во столбцов в первой матрице должно быть = кол-ву строк 2 матрицы
Введите кол-во строк для первой матрицы >2
Введите кол-во столюцов для 1 матрицы >3
Введите кол-во строк для второй матрицы >2
Введите кол-во столбцов для 2 матрицы >3
Кол-во столбцов в первой матрице должно быть = кол-ву строк 2 матрицы
Введите кол-во строк для первой матрицы >2
Введите кол-во столюцов для 1 матрицы >3
Введите кол-во строк для второй матрицы >3
Введите кол-во столбцов для 2 матрицы >2
[[2, 5, 8], [3, 1, 10]]
[[3, 2], [4, 6], [6, 4]]
[[74, 66], [73, 52]]


### Матрицы и матричные операции. Часть 2

##### 1. Вычислить определитель:
   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$\begin{vmatrix}
sinx & -cosx \\
cosx & sinx
\end{vmatrix} = {sin}^2x + {cos}^2x = 1$

$\begin{vmatrix}
4 & 2 & 3 \\
0 & 5 & 1 \\
0 & 0 & 9
\end{vmatrix} = 4\begin{vmatrix}
5 & 1 \\
0 & 9
\end{vmatrix} - 0\begin{vmatrix}
2 & 3 \\
0 & 9
\end{vmatrix} + 0\begin{vmatrix}
2 & 3 \\
5 & 1
\end{vmatrix} = 4 \cdot 45 = 180$

$\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix} = 7\begin{vmatrix}
2 & 3 \\
5 & 6
\end{vmatrix} - 8\begin{vmatrix}
1 & 3 \\
4 & 6
\end{vmatrix} + 9\begin{vmatrix}
1 & 2 \\
4 & 5
\end{vmatrix} = 7 \cdot (12 - 15) - 8 \cdot (6 - 12) + 9 \cdot (5 - 8) = -21 + 48 - 27 = 0$

In [14]:
A = [[4, 2, 3], [0, 5, 1], [0, 0, 9]]
B = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(f'det(A) = {np.linalg.det(A):.0f}')
print(f'det(B) = {np.linalg.det(B):.0f}')

det(A) = 180
det(B) = 0


##### 2.  Определитель матрицы $A$ равен $4$. Найти:  а) $det(A^{2})$;  б) $det(A^{T})$; в) $det(2A)$.

a) 16 б) 4 в) $4\cdot2^{n}$

In [21]:
A = np.matrix([[2, 3, 4], [0, 2, 3], [0, 0, 1]])

print(f'det(A) = {np.linalg.det(A):.0f}')
print(f'det(A*A) = {np.linalg.det(np.dot(A, A)):.0f}')
print(f'det(A.T) = {np.linalg.det(A.T):.0f}')
print(f'det(2*A) = {np.linalg.det(2*A):.0f}')

det(A) = 4
det(A*A) = 16
det(A.T) = 4
det(2*A) = 32


##### 3. Доказать, что матрица
$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$   
вырожденная.

$$\begin{pmatrix}
-2 & 7 & -3 \\
4 & -14 & 6 \\
-3 & 7 & 13
\end{pmatrix} = 7\begin{pmatrix}
4 & 6 \\
-3 & 13
\end{pmatrix} + 14\begin{pmatrix}
-2 & -3 \\
-3 & 13
\end{pmatrix} + 7\begin{pmatrix}
-2 & -3 \\
4 & 6
\end{pmatrix} = 7 \cdot (52+18) + 14 \cdot (-26-9) + 7 \cdot (-12+12) = 490 - 490 = 0$$

In [22]:
A = [[-2, 7, -3], [4, -14, 6], [-3, 7, 13]]

print(f'det(A) = {np.linalg.det(A):.0f}')

det(A) = 0


##### 4. Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

a) $\begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1 \\
2 & 3 & 4
\end{pmatrix} \Rightarrow \begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1
\end{pmatrix} \Rightarrow \begin{pmatrix}
0 & 1 & 2 \\
1 & 1 & 1
\end{pmatrix} \Rightarrow rank = 2$

$\begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 2 & 2 \\
0 & 0 & 4 & 3 \\
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow \begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 2 & 2 \\
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow \begin{pmatrix}
0 & 0 & 0 & -1 \\
0 & 0 & 2 & 2 \\
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow rank = 3$

In [23]:
A = [[1, 2, 3], [1, 1, 1], [2, 3, 4]]
B = [[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]]

print(f'Ранг матрицы A: {np.linalg.matrix_rank(A)}')
print(f'Ранг матрицы B: {np.linalg.matrix_rank(B)}')

Ранг матрицы A: 2
Ранг матрицы B: 3
